src/terminator/Options.java: chrisa's terminator wouldn't start today and he was baffled:
~ $ terminator -xrm 'XTerm*initialColumnCount:132' -xrm 'XTerm*initialRowCount:40'
2006-03-21T13:53:53.218+0000 Terminator: Application started.
2006-03-21T13:53:53.219+0000 Terminator: Java 1.5.0_06 (1.5.0_06-b05).
2006-03-21T13:53:53.219+0000 Terminator: Linux 2.6.15-1-686-smp (i386).
2006-03-21T13:53:53.482+0000 Terminator: Couldn't start Terminator.
Associated exception:
java.lang.RuntimeException: Attempt to set unknown resource "XTerm*initialColumnCount"
        at terminator.Options.processResourceString(Options.java:614)
        at terminator.Options.parseCommandLine(Options.java:244)
        at terminator.Terminator.parseCommandLine(Terminator.java:86)
        at terminator.Terminator.parseOriginalCommandLine(Terminator.java:97)
        at terminator.Terminator.access$200(Terminator.java:13)
        at terminator.Terminator$3.run(Terminator.java:186)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:461)
        at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThread
HangMonitor.java:170)
        at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThrea
d.java:242)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.
java:163)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:157)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:149)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)
~ $ 

If he had followed the suggestion I'm adding here, he'd have at least had a hint that he should try using resources of class Terminator rather than XTerm.  The help also ends in a message explaining that .Xdefaults and .Xresources aren't read - which may also have caused him difficulties.