salma-hayek/lib/build/universal.make: My diagnosis of the build failure in https://github.com/software-jessies-org/jessies/issues/31#issuecomment-513575998 was wrong.  It wasn't the 32 bit chroot, whose use I see I already retired from swiftboat.sh.  It afflicted the 64 bit build too.  The problem is that Debian Jessie's g++ defaults to -std=gnu++98 or some such, causing the like of:
/home/martind/jessies/nightlies/terminator/.generated/native/all/pty/i386_Linux/PtyGenerator.h:225:9: error: identifier ‘nullptr’ is a keyword in C++11 [-Werror=c++0x-compat]

It does support -std=c++11, as I know from work, where we've been shipping product for a couple of years compiled like that.  2019 seems like about time to be switching from an 11 year old standard to an 8 year old one.  We already specify an explicit standard for C compilation.  Let's do it for C++ too.  Iirc, we could go for C++14 without making things difficult for me here.