src/terminator/terminal/PtyProcess.java: src/terminator/terminal/TerminalControl.java: src/terminator/view/JTerminalPane.java: I recently upgraded the C++ library on bertha, causing the JNI library to fail to load:
  java.lang.UnsatisfiedLinkError: /home/elliotth/Projects/terminator/generated/native/all/pty/Linux/libpty.so: /home/elliotth/Projects/terminator/generated/native/all/pty/Linux/libpty.so: undefined symbol: _ZNSt15basic_streambufIcSt11char_traitsIcEE15_M_out_cur_moveEl
  
Handle the error in an appropriate place to show a dialog, rather than expecting the user to hunt around for a log file.