salma-hayek/lib/build/universal.make: TARGET_DIRECTORY wasn't being affected by swiftboat.sh's setting of TARGET_ARCHITECTURE, so I was building eg i386 libpty.so into amd64_Linux, then not overwriting it during the amd64 build.  Move the overriding of the default architecture...
salma-hayek/bin/target-os.rb: ... into the code that sets all such things for all our code.

Caused:

On 16/01/17 12:28, Paul Bland wrote:
I get the following exception when launching Terminator (only seen from this morning):

java.lang.UnsatisfiedLinkError: Failed to load "libpty.so" for amd64 from "/usr/share/software.jessies.org/terminator/Resources/salma-hayek/.generated/amd64_Linux/lib:/usr/share/software.jessies.org/terminator/Resources/terminator/.generated/amd64_Linux/lib"
     at e.util.FileUtilities.throwUnsatisfiedLinkError(FileUtilities.java:419)
     at e.util.FileUtilities.loadNativeLibrary(FileUtilities.java:413)
     at terminator.terminal.PtyProcess.ensureLibraryLoaded(PtyProcess.java:89)
     at terminator.terminal.PtyProcess.<init>(PtyProcess.java:126)
     at terminator.terminal.TerminalControl.initProcess(TerminalControl.java:93)
     at terminator.view.JTerminalPane.init(JTerminalPane.java:163)
     at terminator.view.JTerminalPane.<init>(JTerminalPane.java:39)
     at terminator.view.JTerminalPane.newShellWithName(JTerminalPane.java:87)
     at terminator.TerminatorOpener.getInitialTerminals(TerminatorOpener.java:104)
     at terminator.TerminatorOpener.createUi(TerminatorOpener.java:52)
     at terminator.Terminator.parseOriginalCommandLine(Terminator.java:162)
     at terminator.Terminator.access$200(Terminator.java:15)
     at terminator.Terminator$4.run(Terminator.java:227)
     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
     at java.awt.EventQueue.access$500(EventQueue.java:97)
     at java.awt.EventQueue$3.run(EventQueue.java:709)
     at java.awt.EventQueue$3.run(EventQueue.java:703)
     at java.security.AccessController.doPrivileged(Native Method)
     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
     at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsatisfiedLinkError: /usr/share/software.jessies.org/terminator/Resources/terminator/.generated/amd64_Linux/lib/libpty.so: /usr/share/software.jessies.org/terminator/Resources/terminator/.generated/amd64_Linux/lib/libpty.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
     at java.lang.ClassLoader$NativeLibrary.load(Native Method)
     at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
     at java.lang.Runtime.load0(Runtime.java:809)
     at java.lang.System.load(System.java:1086)
     at e.util.FileUtilities.loadNativeLibrary(FileUtilities.java:401)
     ... 25 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/share/software.jessies.org/terminator/Resources/salma-hayek/.generated/amd64_Linux/lib/libpty.so
     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
     ... 28 more
[Couldn't initialize terminal: UnsatisfiedLinkError.]

I upgrade all packages reported as needing upgrading, but I am still seeing the error.

I cannot launch Evergreen, at all. When I select it from the main menu, there is no response.

I have not seen any issues reported in the jessies/terminator home page. Any ideas what I should do?

Paul