salma-hayek/lib/build/universal.make: Fix compilation with Debian Stretch-era glibc (2.22), which had been failing with:
In file included from /usr/include/stdio.h:27:0,
                 from /usr/lib/jvm/java-9-openjdk-amd64/include/jni.h:39,
                 from /u2/home/mad/jessies/work/salma-hayek/native/Headers/PortableJni.h:13,
                 from /u2/home/mad/jessies/work/salma-hayek/.generated/native/all/posix/amd64_Linux/org_jessies_os_PosixJNI.h:3,
                 from /u2/home/mad/jessies/work/salma-hayek/.generated/native/all/posix/amd64_Linux/org_jessies_os_PosixJNI.cpp:6:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1plus: all warnings being treated as errors
<builtin>: recipe for target '/u2/home/mad/jessies/work/salma-hayek/.generated/native/all/posix/amd64_Linux/org_jessies_os_PosixJNI.o' failed
make[2]: *** [/u2/home/mad/jessies/work/salma-hayek/.generated/native/all/posix/amd64_Linux/org_jessies_os_PosixJNI.o] Error 1

Given that we don't care whether we get the Gnu or the Posix strerror_r, and that it's been in Posix since 2001, perhaps we could just delete this whole nugget.  The machine referenced in the comment, gooch, shuffled off this mortal coil many a year ago.  The BlueArc bug database says it was probably running libc 2.2.