native/Mingw/cygwin-launcher/cygwin-launcher.cpp: Looks like 2014-08-28, the Cygwin Ruby maintainer removed rubyw.exe with:
http://sourceforge.net/p/cygwin-ports/ruby/ci/1d0f8e5fb9e999a0f5d7d15058a2b23fba6c7645/

After upgrading Cygwin, in order to try (and fail) to reproduce an AlH issue about "Check Compatibility" and "Run as Administrator", this gave me a monologue box when starting Terminator from the icon, informing us that:

Error: couldn't read Cygwin Rubyw (Ruby with no console window) from "C:\cygwin64\bin\rubyw.exe"

Now, why do we need rubyw instead of ruby?  It's to stop the console window that we otherwise get while running the terminator script.  But I no longer get that console window, even if I stick a "sleep(10)" in bin/terminator.  I do still get a console window if I do c:\cygwin64\bin\ruby -e 'sleep 10' in the Start, Run box.  But not if I do c:\Program Files\software.jessies.org\terminator\Resources\salma-hayek\.generated\amd64_Cygwin\bin\ruby-launcher.exe c:\cygwin64\ruby.exe -e 'sleep 10'.  I guess that the ensureDescriptorIsOpen code did enough, though c:\cygwin64\bin\ruby -e 'sleep 10' > C:\file 2> C:\file still gives me a console window.