native/all/pty/terminator_terminal_PtyProcess.cpp: The Win32 jni_md.h depends on __int64 but cygwin doesn't define it.  Subversion's accidentally recursive commit command caused me to inadvertently check-in a version where everything's stubbed out on Win32.  The reason for the stubbing out of all the entry points of Win32 was to try compiling with -mno-cygwin to prove that that produced a working DLL, albeit a useless one.  Compiling without that flag caused this:
Serious error: cannot load libpty.
java.lang.UnsatisfiedLinkError: F:\software.jessies.org\terminator\generated\native\all\libpty\CYGWIN_NT-5.0\pty.dll: Invalid access to memory location
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(Unknown Source)
at java.lang.ClassLoader.loadLibrary(Unknown Source)
at java.lang.Runtime.loadLibrary0(Unknown Source)
at java.lang.System.loadLibrary(Unknown Source)
at terminator.terminal.PtyProcess.ensureLibrary(PtyProcess.java:19)

The stubbing out suggested that it wasn't our fault.  Mumit suggested (http://www.cygwin.com/ml/cygwin/1999-05/msg00318.html) running under gdb.

Program received signal SIGSEGV, Segmentation fault.
[Switching to thread 296.0x63c]
0x61075da0 in cygwin_split_path ()
(gdb) bt
#0  0x61075da0 in cygwin_split_path ()
#1  0x61076002 in cygwin_split_path ()
#2  0x610064c4 in toascii ()
#3  0x61006ad0 in dll_crt0@0 ()
#4  0x6101dc4b in dll_dllcrt0 ()
#5  0x49031428 in _cygwin_dll_entry@12 ()
#6  0x77f830e7 in ?? ()
#7  0x49030000 in ?? ()
#8  0x00000001 in ?? ()
#9  0x00000000 in ?? () from
(gdb)