native/Headers/unix_exception.h: This message (from evan's dchroot):
java.io.IOException: posix_openpt(O_RDWR | O_NOCTTY) failed

... sent me rushing to the source to find why we weren't displaying the value of errno.

We don't want to use strerror_r (or friends) on an errno of zero because that will say "no error" and there's clearly an error.  (That's why we don't want to just append errnoToString().)