src/terminator/TerminatorPreferences.java: We now have code for Windows which alleges to do opacity setting.  It is only expected to work in 6u10 or greater, though no-one has tested that.  In earlier releases, it'll spew exceptions into the log, below a message intimating that we've trapped them harmlessly in the setFrameAlpha method.  Someone might be along to disable the slider if the JRE provably doesn't support setting the opacity but we need to enable it on Windows for now if anyone is to test the new code.
2008-09-19T14:16:09.908-0700 Terminator: Failed to apply frame alpha.
Associated exception:
java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at e.util.GuiUtilities.setFrameAlpha(GuiUtilities.java:346)
	at terminator.TerminatorFrame.updateTransparency(TerminatorFrame.java:366)
	at terminator.TerminatorFrame.addNotify(TerminatorFrame.java:362)
	at java.awt.Window.pack(Unknown Source)
	at terminator.TerminatorFrame.initFrame(TerminatorFrame.java:83)
	at terminator.TerminatorFrame.<init>(TerminatorFrame.java:26)
	at terminator.Terminator$3.run(Terminator.java:181)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThreadHangMonitor.java:191)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)