src/terminator/Frames.java: Fix build breakage introduced with r1597 on both non-Mac platforms:
src/terminator/Frames.java:44: cannot find symbol
symbol  : method setDockMenu(java.awt.PopupMenu)
location: class com.apple.eawt.Application
            Application.getApplication().setDockMenu(dockMenu);
                                        ^
1 error

We hope this code will never be called except on a Mac, though that isn't quite obvious from the callers, specifically from getFrame, which, as Ed says, is probably a mistake.  Even so, we need to deal with two checked exceptions, NoSuchMethodException and IllegalAccessException.

Apparently, there's no new version of AppleJavaExtensions.jar, with this method, available.