src/e/edit/TagType.java: Susi got this:
2009-01-28T11:57:17.818-0800 Evergreen: Problem creating backup file before saving "~/work/eaglecrest2/axalon/manager/web/templates/app/screens/protocols/ShareList.vm"
Associated exception:
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:706)
	at java.util.regex.Matcher.replaceAll(Matcher.java:806)
	at java.lang.String.replaceAll(String.java:2000)
	at e.edit.TagType.describe(TagType.java:78)
	at e.edit.TagReader$Tag.describe(TagReader.java:260)
	at e.edit.TagReader$Tag.toString(TagReader.java:264)
	at javax.swing.tree.DefaultMutableTreeNode.toString(DefaultMutableTreeNode.java:1229)
	at javax.swing.JTree.convertValueToText(JTree.java:1139)
	at javax.swing.tree.DefaultTreeCellRenderer.getTreeCellRendererComponent(DefaultTreeCellRenderer.java:331)
	at e.edit.TagsPanel$TagsTreeRenderer.getTreeCellRendererComponent(TagsPanel.java:108)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2693)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:475)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1342)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.getXOrigin(VariableHeightLayoutCache.java:1125)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.getNodeBounds(VariableHeightLayoutCache.java:1108)
	at javax.swing.tree.VariableHeightLayoutCache.getBounds(VariableHeightLayoutCache.java:202)
	at javax.swing.plaf.basic.BasicTreeUI.getPathBounds(BasicTreeUI.java:511)
	at javax.swing.JTree.getPathBounds(JTree.java:1642)
	at e.gui.ETree.scrollPathToVisible(ETree.java:82)
	at e.edit.TagsUpdater.selectTreeNode(TagsUpdater.java:200)
	at e.edit.TagsUpdater.selectTagAtCaret(TagsUpdater.java:87)
	at e.edit.TagsUpdater.access$200(TagsUpdater.java:15)
	at e.edit.TagsUpdater$3.caretMoved(TagsUpdater.java:78)
	at e.ptextarea.PTextArea.fireCaretChangedEvent(PTextArea.java:153)
	at e.ptextarea.PTextArea.setSelectionWithoutScrolling(PTextArea.java:266)
	at e.ptextarea.PTextArea.setSelection(PTextArea.java:233)
	at e.ptextarea.PTextArea.select(PTextArea.java:227)
	at e.edit.ETextWindow.writeToFile(ETextWindow.java:750)
	at e.edit.ETextWindow.save(ETextWindow.java:685)
	at e.edit.SaveAction.actionPerformed(SaveAction.java:18)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1849)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2169)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:420)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:302)

She was trying to save some kind of file that had been treated by Evergreen as XML.  Extra debugging revealed that the "identifier" in question was:

2009-01-28T13:35:31.562-0800 Evergreen: identifier == #renderPageNavJavascript($shares)

The code fragment including that was:

<link href="/css/axalon.css" rel="styleSheet" type="text/css">
#renderPageNavJavascript($shares)
<div align="center">

Pattern.quote didn't help.  I didn't try StringUtilities.regularExpressionFromLiteral though I believe it would have done the trick, because it would have changed other characters that shouldn't be changed.  It might well be that none of them would ever have caused a problem but that still leaves a nasty taste in mouth from not revealing the intention.  Hmm, shouldn't the method names "regularExpressionFromLiteral" and now "replacementStringFromLiteral" be verbized?