src/e/util/FileUtilities.java: /home/martindo startsWith /home/martind but isn't under my home directory.  Fixes:
2008-08-18T10:31:57.498-0700 Evergreen: in ContentLoader exception handler
Associated exception:
java.lang.RuntimeException: java.io.FileNotFoundException: ~o/badger (No such file or directory)
	at e.ptextarea.PTextBuffer.readFromFile(PTextBuffer.java:165)
	at e.edit.ETextWindow.fillWithContent(ETextWindow.java:325)
	at e.edit.ETextWindow.<init>(ETextWindow.java:95)
	at e.edit.Workspace.addViewerForFile(Workspace.java:181)
	at e.edit.Evergreen.openFileNonInteractively(Evergreen.java:340)
	at e.edit.Evergreen.openFileNonInteractively(Evergreen.java:236)
	at e.edit.EditServer$Opener.run(EditServer.java:55)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
	at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThreadHangMonitor.java:191)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:273)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:183)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:173)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:168)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:160)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:121)
Caused by: java.io.FileNotFoundException: ~o/badger (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at e.ptextarea.PTextBuffer.readFromFile(PTextBuffer.java:152)
	... 15 more