evergreen/lib/scripts/ediff.py: Python3 compatibility:
    print '--- %s' % label1
                 ^
SyntaxError: Missing parentheses in call to 'print'