salma-hayek/lib/build/vxd0141.sh: My main obstacle in getting exim to work again was seemingly the need for a Cygwin update, but there were a number of other smaller obstacles, with HDS's firewall, with a change I made to sidestep Ruby 1.8 in my 32 bit Squeeze chroot, with exim's automatic determination of the primary hostname and my previous effort at a smarthost router.
salma-hayek/lib/build/universal.make: Cygwin's lost the prototype of ptsname and friends without a Linux-like _XOPEN_SOURCE definition.

Cygwin helpfully points out that find -name ../.git is never going to match anything:

mdorey@VXD0141 ~/jessies/work/salma-hayek
$ make echo.BOOT_JDK
make[1]: Entering directory '/home/mdorey/jessies/work/salma-hayek'
find: warning: Unix filenames usually don't contain slashes (though pathnames do).  That means that '-name ‘../.git’' will probably evaluate to false all the time on this system.  You might find the '-wholename' test more useful, or perhaps '-samefile'.  Alternatively, if you are using GNU grep, you could use 'find ... -print0 | grep -FzZ ‘../.git’'.
""
make[1]: Leaving directory '/home/mdorey/jessies/work/salma-hayek'

mdorey@VXD0141 ~/jessies/work/salma-hayek

For the purposes of ignoring that directory, we don't care.

salma-hayek/lib/build/per-directory.make: The spurious semicolon here should terminate the rule for refreshing the JNI header but from the newly generated version, if it's different.  I just happened to notice it looking at the source - for some reason, it doesn't seem to matter at runtime.

salma-hayek/lib/build/uuid.rb:
salma-hayek/lib/User32.rb: Cygwin's dlopen no longer appends ".dll" implicitly, per http://superuser.com/questions/1093954/gem-not-working-in-cygwin.

salma-hayek/lib/build/per-directory.make: Revert to assembling the source and headers use cp rather than ln -s...

salma-hayek/lib/build/universal.make: ... on Cygwin, to work around this:

mdorey@VXD0141 ~
$ /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/cc1.exe -quiet `pwd`/j/s/g/b/build/hello.c -o /tmp/ccDD174B.s
/home/mdorey/j/s/g/b/build/hello.c:1:19: fatal error: hello.h: No such file or directory
compilation terminated.

mdorey@VXD0141 ~
$ ls -l `pwd`/j/s/g/b/build/hello.c                                             lrwxrwxrwx 1 mdorey Domain Users 29 Jan  9 23:33 /home/mdorey/j/s/g/b/build/hello.c -> ../../../../../source/hello.c

mdorey@VXD0141 ~
$ cat `pwd`/j/s/g/b/build/hello.c
#include "hello.h"

int main() {
    return 0;
}

mdorey@VXD0141 ~
$ ls -l `pwd`/j/s/g/b/build/hello.h
-rw-r--r-- 1 mdorey Domain Users 0 Jan  9 22:12 /home/mdorey/j/s/g/b/build/hello.h

mdorey@VXD0141 ~
$

It doesn't matter whether the symlink is relative or absolute.  Our code here uses absolute links, unlike the above example.  It doesn't matter where the link goes to.  It does matter how many components there are in the directory containing the link.

strace you'd think would be the next step but it always crashes for me, in KERNEL32!GetVolumePathNamesForVolumeNameW, much as for https://cygwin.com/ml/cygwin/2016-04/msg00213.html but without the strange DLL injections that ran that thread into the sand with https://cygwin.com/ml/cygwin/2016-04/msg00218.html.  /var/log/setup.log suggests that I previously had gcc-4.9.3 and cygwin 2.4.1, when I didn't see this problem.  clang evinces no such problem, for what that's worth.  Cygwin's setup would let me downgrade gcc to 5.3.0.  That still failed.  It let me downgrade Cygwin to 2.4.0.  That still failed.  Going back to the latest Cygwin and trying cc1.exe from http://cygwin.mirror.constant.com/x86_64/release/gcc/gcc-core/gcc-core-4.9.3-1.tar.xz worked.  The next available version, http://cygwin.mirror.constant.com/x86_64/release/gcc/gcc-core/gcc-core-5.2.0-1.tar.xz, didn't.