src/terminator/view/JTextBuffer.java: Fix a problem with small windows which I can trivially reproduce on Linux but which seemingly doesn't happen on Mac OS.  We should perhaps catch this earlier - say in TextBuffer.setSize - and so prevent invalid model sizes from being set, rather than trying to cope with the fall-out.  I don't think that would be quite enough to stop the cursor from being positioned at an invalid location.
2006-04-16T13:18:26.688-0700 Terminator: Failed to notify PtyProcess[processId=13451,fd=30,pty="/dev/pts/5",didDumpCore=false,didExitNormally=false,wasSignaled=false,exitValue=0] of size change
Associated exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1762)
	at terminator.view.JTextBuffer.modelToView(JTextBuffer.java:397)
	at terminator.view.JTextBuffer.redrawCursorPosition(JTextBuffer.java:631)
	at terminator.view.JTextBuffer.setCursorPosition(JTextBuffer.java:337)
	at terminator.model.TextBuffer.processActions(TextBuffer.java:330)
	at terminator.terminal.TerminalControl.sizeChanged(TerminalControl.java:228)
	at terminator.view.JTerminalPane$1SizeMonitor.componentResized(JTerminalPane.java:179)
	at java.awt.Component.processComponentEvent(Component.java:5314)
	at java.awt.Component.processEvent(Component.java:5268)
	at java.awt.Container.processEvent(Container.java:1966)
	at java.awt.Component.dispatchEventImpl(Component.java:3955)
	at java.awt.Container.dispatchEventImpl(Container.java:2024)
	at java.awt.Component.dispatchEvent(Component.java:3803)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
	at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThreadHangMonitor.java:192)
	at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:157)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:149)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)