bin/edit: The MRJ stubs have moved to salma-hayek in Elliott's last change.  Apparently it works for him because he can find the real (non-stubbed) version of com/apple/eawt/ApplicationListener on his Mac.  This was the error that was happening on Linux:
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)

scmtool needed changing too.  As Elliott mumbled before lunch, we should abstract-out more of this.  We could do with a script equivalent of java.make that deals with invoking the tool rather than compiling it.