src/org/jessies/test/TestRunner.java: We could just ignore unexpected files, but crashing seems a bit poor:
martind@whitewater:~/software.jessies.org/work/salma-hayek$ ./bin/org.jessies.TestRunner .generated/native/
Exception in thread "main" java.lang.NullPointerException
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:96)
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:103)
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:103)
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:103)
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:103)
	at org.jessies.test.TestRunner.findClassNames(TestRunner.java:85)
	at org.jessies.test.TestRunner.findTests(TestRunner.java:65)
	at org.jessies.test.TestRunner.runTests(TestRunner.java:60)
	at org.jessies.test.TestRunner.main(TestRunner.java:55)
martind@whitewater:~/software.jessies.org/work/salma-hayek$

Failing gracefully, indicating the reason, seems a better choice:

martind@whitewater:~/software.jessies.org/work/salma-hayek$ ./bin/org.jessies.TestRunner .generated/native/
ERROR: '.generated/native/all/setsid/amd64_Linux/setsid.cpp' is not a directory or a .class file
martind@whitewater:~/software.jessies.org/work/salma-hayek$