src/e/edit/Diffable.java: I should be able to close a file that has modifications but which has been renamed underneath Evergreen.  I contemplated not caching the result but that would have required a code-comment that I couldn't find plausible wording for.
2009-07-28T17:12:09.821-0700 Evergreen: Exception occurred during event dispatching.
Associated exception:
java.lang.RuntimeException: java.io.FileNotFoundException: /home/martind/work/tiger/fsb/fsi/FSIReadCacheNotifierPoolSize.h (No such file or directory)
	at e.util.StringUtilities.readFileAsCharArray(StringUtilities.java:44)
	at e.util.StringUtilities.readFile(StringUtilities.java:32)
	at e.edit.Diffable.content(Diffable.java:74)
	at e.edit.SimplePatchDialog.makePatchView(SimplePatchDialog.java:118)
	at e.edit.SimplePatchDialog.makeScrollablePatchView(SimplePatchDialog.java:34)
	at e.edit.SimplePatchDialog.makeDialog(SimplePatchDialog.java:207)
	at e.edit.SimplePatchDialog.showPatchBetween(SimplePatchDialog.java:199)
	at e.edit.ETextWindow.showPatchAndAskForConfirmation(ETextWindow.java:437)
	at e.edit.ETextWindow.closeWindow(ETextWindow.java:478)
	at e.edit.ECloseButton.actionPerformed(ECloseButton.java:54)
	at e.edit.EButton.mouseReleased(EButton.java:35)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:272)
	at java.awt.Component.processMouseEvent(Component.java:6263)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
	at java.awt.Component.processEvent(Component.java:6028)
	at java.awt.Container.processEvent(Container.java:2041)
	at java.awt.Component.dispatchEventImpl(Component.java:4630)
	at java.awt.Container.dispatchEventImpl(Container.java:2099)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4574)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
	at java.awt.Container.dispatchEventImpl(Container.java:2085)
	at java.awt.Window.dispatchEventImpl(Window.java:2475)
	at java.awt.Component.dispatchEvent(Component.java:4460)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:599)
	at e.debug.EventDispatchThreadHangMonitor.dispatchEvent(EventDispatchThreadHangMonitor.java:191)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.io.FileNotFoundException: /home/martind/work/tiger/fsb/fsi/FSIReadCacheNotifierPoolSize.h (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at e.util.ByteBufferUtilities.readFile(ByteBufferUtilities.java:23)
	at e.util.StringUtilities.readFileAsCharArray(StringUtilities.java:37)
	... 32 more

src/e/edit/SimplePatchDialog.java: With the above change, the patch presented is still wrong, even when useInternalDiff is changed to false.  That's easily fixed, here, by the addition of -N.  I'll have a look at that next but a cosmetic issue in this file is sticking in my craw and I want to address that first, in a separate check-in.